#!/usr/bin/env bash
# Bash script that transfers a file to a remote server using SCP

# Check if less than 4 parameters were passed
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Use scp to copy the file to the user's home directory on the server
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"

