#!/usr/bin/env bash
# Configure Nginx with custom HTTP header X-Served-By

# Install nginx
apt-get update -y
apt-get install -y nginx

# Set hostname
hostnamectl set-hostname 03-web-01
HOSTNAME=$(hostname)

# Modify Nginx config
CONFIG="/etc/nginx/sites-available/default"
sed -i "/location \/ {/a \    add_header X-Served-By \"$HOSTNAME\";" "$CONFIG"

# Restart Nginx
nginx -t && systemctl restart nginx

