#!/usr/bin/env bash
# Script to install and configure HAProxy for roundrobin load balancing between two web servers

# Ensure running as root
if [ "$EUID" -ne 0 ]; then
  echo " Please run as root or use sudo"
  exit 1
fi

# Install haproxy
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy in default config
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon
    maxconn 256

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 172.25.226.73 172.18.0.1 172.17.0.1:80 check
    server web-02 197.185.158.121:80 check
EOF

# Restart HAProxy to apply changes
systemctl restart haproxy

